version: '3'

services:

  tb:
    build: .
    env_file:
      - .env
    depends_on:
      - psql

  psql:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: lkafghiwshf234
      POSTGRES_USER: andy
      POSTGRES_DB: tb
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
